package:
  name: imageio
  version: "1.3.0"

source:
  fn: imageio-1.3.tar.gz
  url: https://pypi.python.org/packages/source/i/imageio/imageio-1.3.tar.gz
  md5: 823e7831e2421025578cfe7c0902988b

requirements:
  build:
    - python
    - numpy
    - setuptools
    - freeimage 3.17.*

  run:
    - python
    - numpy
    - freeimage 3.17.*

test:
  imports:
    - imageio

about:
  home: http://imageio.github.io/
  license: BSD
